"""Arkiflo Configuration"""

from .constants import (
    VALID_ROLES, PAYMENT_MODES, PAYMENT_SCHEDULE_TYPES,
    TASK_PRIORITIES, TASK_STATUSES, MEETING_STATUSES, NOTIFICATION_TYPES
)
from .tat import (
    LEAD_TAT, PROJECT_TAT, LEAD_STAGES, LEAD_MILESTONES,
    STAGE_ORDER, MILESTONE_GROUPS,
    DEFAULT_LEAD_TAT, DEFAULT_PROJECT_TAT,
    DEFAULT_STAGES, DEFAULT_LEAD_STAGES
)
from .financials import DEFAULT_PAYMENT_SCHEDULE
from .email_templates import DEFAULT_EMAIL_TEMPLATES

__all__ = [
    # Constants
    'VALID_ROLES', 'PAYMENT_MODES', 'PAYMENT_SCHEDULE_TYPES',
    'TASK_PRIORITIES', 'TASK_STATUSES', 'MEETING_STATUSES', 'NOTIFICATION_TYPES',
    # TAT Configuration
    'LEAD_TAT', 'PROJECT_TAT', 'LEAD_STAGES', 'LEAD_MILESTONES',
    'STAGE_ORDER', 'MILESTONE_GROUPS',
    'DEFAULT_LEAD_TAT', 'DEFAULT_PROJECT_TAT',
    'DEFAULT_STAGES', 'DEFAULT_LEAD_STAGES',
    # Financials
    'DEFAULT_PAYMENT_SCHEDULE',
    # Email Templates
    'DEFAULT_EMAIL_TEMPLATES',
]
